### ISSUE TITLE
Problem in slider of social conciousness page

### ISSUE THREAD

**Issue by code-ash-IIT** [KamandPrompt/studentsweb#104]
I have resized images as the issue was assigned to me. No changes to any html file was made.
For my changes to reflect on SOCIAL_CONCIOUSNESS page please edit html file (@vaidehi44 you may have a look at this issue).

**Comment by code-ash-IIT** [comment]
Look into this after my pr #103 is merged.

**Comment by vaidehi44** [comment]
Actually, I was going to resize the images once I complete the development job. But, if your are doing, well and good :). But, I didn't get the title of issue. Is there any problem in slider/carousel or only with the size of images?

**Comment by code-ash-IIT** [comment]
I've checked this issue in recent changes. Now everything looks fine. Previously due to different sizes of images, slider next and prev were not fully functional for all images.
So, i'm closing this issue now :)
