### ISSUE TITLE
Fix Indian Institute of Technology in title bar on small screened devices

### ISSUE THREAD

**Issue by LalitNM** [KamandPrompt/studentsweb#124]
Here is a screenshot, this doesn't look good.
![image](https://user-images.githubusercontent.com/63332774/137614353-57f0c905-5dd8-48ff-abc0-ed355e462b25.png)

**Comment by code-ash-IIT** [comment]
@LalitNM bhai, please provide short form of iit in hindi

**Comment by LalitNM** [comment]
This should work - `भा. प्रौ. सं. मण्डी`.
