### ISSUE TITLE
Merge team4 completely

### ISSUE THREAD

**Issue by LalitNM** [KamandPrompt/studentsweb#93]
@vaidehi44 there was a commit in your branch `team4` after I merged it into `main`, would you like to merge those into `main`.

**Comment by vaidehi44** [comment]
Yes. We can merge it. And, should I directly push changes to main now ?

**Comment by LalitNM** [comment]
No, we don't push anything directly to `main` normally, make pull request and get atleast one review on it, then we can merge it into `main`.

**Comment by vaidehi44** [comment]
Alright.

**Comment by vaidehi44** [comment]
Yes, we can close.
